(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.tnc2_sub = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAHIAAgNIALAAIAAANg");
	this.shape.setTransform(249.7,80.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_1.setTransform(245.2,78.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_2.setTransform(241.1,77.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGAfQgEgFAAgJIAAgdIgGAAIAAgHIAGAAIAAgPIAJAAIAAAPIASAAIAAAHIgSAAIAAAYIAAAIIABAEIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHgBgFgEg");
	this.shape_3.setTransform(237.8,77.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOg");
	this.shape_4.setTransform(232.5,78.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgGIgEgCIgGgBQgDAAgEABIgIAGIAAAnIgJAAIAAg2IAJAAIAAAHIAJgGQAEgCAFAAQAJAAAEAGQAFAEAAAKIAAAjg");
	this.shape_5.setTransform(226.4,78.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_6.setTransform(220.2,78.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgGIgEgCIgGgBQgDAAgEABIgIAGIAAAnIgJAAIAAg2IAJAAIAAAHIAJgGQAEgCAFAAQAJAAAEAGQAFAEAAAKIAAAjg");
	this.shape_7.setTransform(214,78.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_8.setTransform(207.7,78.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgEAbIgVg1IAKAAIAQAqIAQgqIAKAAIgXA1g");
	this.shape_9.setTransform(201.7,78.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGAfQgEgFAAgJIAAgdIgGAAIAAgHIAGAAIAAgPIAJAAIAAAPIASAAIAAAHIgSAAIAAAYIAAAIIABAEIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHgBgFgEg");
	this.shape_10.setTransform(193.2,77.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgGIgEgCIgGgBQgDAAgEABIgIAGIAAAnIgJAAIAAg2IAJAAIAAAHIAJgGQAEgCAFAAQAJAAAEAGQAFAEAAAKIAAAjg");
	this.shape_11.setTransform(187.9,78.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgRAXQgFgGAAgJIAAgjIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAABIAGABQADAAAEgCIAIgGIAAgnIAJAAIAAA2IgJAAIAAgHIgJAGQgEACgEAAQgJAAgFgFg");
	this.shape_12.setTransform(181.5,78.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgRAfQgGgHAAgOQAAgHACgEQABgFAEgEQAEgEAEgCQAFgCADAAIAIABIAHADIAAgYIAJAAIAABLIgJAAIAAgFIgIAFQgFACgEAAQgKAAgFgIgAgJgEQgFAEAAAKQAAAKAEAFQADAFAHAAQADAAAEgCQAEgBAEgDIAAgeIgHgDIgHAAQgGAAgEAFg");
	this.shape_13.setTransform(175,77.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_14.setTransform(170.6,77.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgFAbQgFgCgEgEQgDgDgCgFQgCgGAAgGQAAgNAHgIQAIgHALgBIAJACIAIADIAAAKIAAAAQgFgDgEgBQgFgDgEAAQgHAAgEAGQgFAFAAAKQAAAJAFAFQAEAGAHAAIAGgBIAFgCIAEgCIADgCIAAAAIAAAKIgJAEIgIABQgFgBgFgBg");
	this.shape_15.setTransform(166.7,78.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgGIgEgCIgGgBQgDAAgEABIgIAGIAAAnIgJAAIAAg2IAJAAIAAAHIAJgGQAEgCAFAAQAJAAAEAGQAFAEAAAKIAAAjg");
	this.shape_16.setTransform(160.7,78.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_17.setTransform(156.1,77.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgGAfQgEgFAAgJIAAgdIgGAAIAAgHIAGAAIAAgPIAJAAIAAAPIASAAIAAAHIgSAAIAAAYIAAAIIABAEIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHgBgFgEg");
	this.shape_18.setTransform(152.8,77.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgGAfQgEgFAAgJIAAgdIgGAAIAAgHIAGAAIAAgPIAJAAIAAAPIASAAIAAAHIgSAAIAAAYIAAAIIABAEIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHgBgFgEg");
	this.shape_19.setTransform(145.2,77.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgDAbIgXg1IAKAAIAQAqIARgqIAJAAIgVA1g");
	this.shape_20.setTransform(140.1,78.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_21.setTransform(134.1,78.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgJAmIgIgCIAAgJIAAAAIAHACIAKABIAHgBIAEgDIADgFIABgGIAAgFQgFAEgDABQgEACgFAAQgKAAgFgHQgGgHAAgMQAAgHACgFQABgFAEgEQAEgDAEgCQAFgCADAAIAIABIAHADIAAgDIAJAAIAAAwQAAANgGAHQgHAGgMAAIgIAAgAgJgYQgFAFAAAKQAAAJAEAEQADAEAHAAIAHgBIAIgEIAAgdIgHgCIgHgBQgGAAgEAFg");
	this.shape_22.setTransform(127.8,79.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_23.setTransform(121.7,78.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgGAfQgEgFAAgJIAAgdIgGAAIAAgHIAGAAIAAgPIAJAAIAAAPIASAAIAAAHIgSAAIAAAYIAAAIIABAEIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHgBgFgEg");
	this.shape_24.setTransform(113.2,77.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_25.setTransform(109.7,77.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgEAmIAAhLIAJAAIAABLg");
	this.shape_26.setTransform(106.9,77.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_27.setTransform(102.5,78.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgKAQIAJgfIAMAAIgNAfg");
	this.shape_28.setTransform(94,81.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_29.setTransform(89.6,78.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_30.setTransform(83.8,78.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgEAmIAAhLIAJAAIAABLg");
	this.shape_31.setTransform(79.4,77.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOg");
	this.shape_32.setTransform(74.8,78.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgRAfQgGgHAAgOQAAgHACgEQACgFADgEQAEgEAEgCQAFgCADAAIAIABIAGADIAAgYIAKAAIAABLIgKAAIAAgFIgIAFQgEACgEAAQgKAAgFgIgAgJgEQgFAEAAAKQAAAKADAFQAEAFAHAAQADAAAEgCQAEgBADgDIAAgeIgGgDIgGAAQgHAAgEAFg");
	this.shape_33.setTransform(68.6,77.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_34.setTransform(62.5,78.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_35.setTransform(56.9,78.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAfAcIAAgeIgBgHIgBgFIgDgDQgCgCgEABQgEAAgEABIgIAGIABACIAAADIAAAiIgJAAIAAgeIAAgHIgBgFIgDgDQgCgCgEABQgEAAgEABIgIAGIAAAnIgJAAIAAg2IAJAAIAAAHIAJgGQAEgCAFAAQAGAAAEACQACACACAFQAGgFAFgCQAEgCAFAAQAJAAAFAGQAEAFAAAJIAAAjg");
	this.shape_36.setTransform(45.7,78.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOg");
	this.shape_37.setTransform(37.5,78.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_38.setTransform(33.3,77.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgGAfQgEgFAAgJIAAgdIgGAAIAAgHIAGAAIAAgPIAJAAIAAAPIASAAIAAAHIgSAAIAAAYIAAAIIABAEIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHgBgFgEg");
	this.shape_39.setTransform(29.9,77.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgXAkIAAhHIAvAAIAAAIIglAAIAAAUIAlAAIAAAIIglAAIAAAbIAlAAIAAAIg");
	this.shape_40.setTransform(24.9,77.5);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgFAHIAAgNIALAAIAAANg");
	this.shape_41.setTransform(265,66.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_42.setTransform(260.6,64.3);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgEAkIAAg1IAJAAIAAA1gAgEgaIAAgKIAJAAIAAAKg");
	this.shape_43.setTransform(256.5,63.4);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgEAmIAAhLIAJAAIAABLg");
	this.shape_44.setTransform(253.7,63.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_45.setTransform(249.2,64.3);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgKAmIAAguIgHAAIAAgHIAHAAIAAgCQAAgKAEgFQAFgFAJAAIAFAAIAFABIAAAIIgBAAIgEgBIgEAAQgGAAgDACQgBADAAAHIAAACIAPAAIAAAHIgPAAIAAAug");
	this.shape_46.setTransform(244.8,63.2);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_47.setTransform(236,64.3);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgRAXQgFgGAAgKIAAgiIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAABIAGABQADAAAEgDIAIgEIAAgoIAJAAIAAA1IgJAAIAAgFIgJAFQgEACgEAAQgJAAgFgFg");
	this.shape_48.setTransform(229.7,64.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AAPAmIAAgaQgEAEgFACQgEABgEAAQgJAAgHgIQgFgHAAgMQAAgHACgFQACgGADgDQAEgEAEgCQAEgCAEAAIAIABIAHADIAAgCIAJAAIAABJgAgJgYQgFAGAAAKQAAAIAEAFQADAFAHAAQADAAAEgBQAEgCAEgDIAAgeIgHgCIgHgBQgGAAgEAFg");
	this.shape_49.setTransform(223.3,65.2);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_50.setTransform(217.7,64.3);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_51.setTransform(211.9,64.3);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgGAfQgEgFAAgKIAAgcIgGAAIAAgHIAGAAIAAgPIAJAAIAAAPIASAAIAAAHIgSAAIAAAYIAAAIIABAEIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHAAgFgFg");
	this.shape_52.setTransform(207,63.6);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgGIgEgCIgGgBQgDAAgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAGIAJgGQAEgCAFAAQAJAAAEAFQAFAGAAAKIAAAig");
	this.shape_53.setTransform(201.7,64.2);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_54.setTransform(195.5,64.3);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgEAmIAAhLIAJAAIAABLg");
	this.shape_55.setTransform(191.1,63.2);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgEAmIAAhLIAJAAIAABLg");
	this.shape_56.setTransform(188.3,63.2);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_57.setTransform(183.8,64.3);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgXAmIAAhJIAJAAIAAAFIAJgFQAEgCAEAAQAKAAAGAIQAFAHAAANQAAAGgCAFQgCAFgDAEQgEAEgEACQgEACgFAAIgHgBIgHgCIAAAWgAgGgaIgIAEIAAAeIAHACIAGABQAHAAAFgFQADgGAAgIQABgKgEgGQgDgEgHAAQgDAAgEACg");
	this.shape_58.setTransform(177.9,65.2);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgGAfQgEgFAAgKIAAgcIgGAAIAAgHIAGAAIAAgPIAJAAIAAAPIASAAIAAAHIgSAAIAAAYIAAAIIABAEIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHAAgFgFg");
	this.shape_59.setTransform(169,63.6);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_60.setTransform(163.9,64.3);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AAfAcIAAgeIgBgHIgBgFIgDgDQgCgBgEAAQgEAAgEACIgIAEIABADIAAADIAAAiIgJAAIAAgeIAAgHIgBgFIgDgDQgCgBgEAAQgEAAgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAGIAJgGQAEgCAFAAQAGAAAEACQACADACAEQAGgFAFgCQAEgCAFAAQAJAAAFAFQAEAGAAAKIAAAig");
	this.shape_61.setTransform(156,64.2);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOg");
	this.shape_62.setTransform(147.8,64.3);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AgGAfQgEgFAAgKIAAgcIgGAAIAAgHIAGAAIAAgPIAJAAIAAAPIASAAIAAAHIgSAAIAAAYIAAAIIABAEIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHAAgFgFg");
	this.shape_63.setTransform(139.4,63.6);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AgEAkIAAg1IAJAAIAAA1gAgEgaIAAgKIAJAAIAAAKg");
	this.shape_64.setTransform(136,63.4);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_65.setTransform(132,64.3);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_66.setTransform(122.6,64.3);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("AgRAXQgFgGAAgKIAAgiIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAABIAGABQADAAAEgDIAIgEIAAgoIAJAAIAAA1IgJAAIAAgFIgJAFQgEACgEAAQgJAAgFgFg");
	this.shape_67.setTransform(116.4,64.4);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AAOAmIAAgaQgEAEgEACQgEABgEAAQgKAAgFgIQgGgHAAgMQAAgHACgFQACgGADgDQADgEAFgCQAEgCAEAAIAHABIAHADIABgCIAJAAIAABJgAgKgYQgEAGAAAKQAAAIADAFQAEAFAHAAQADAAAEgBQAEgCADgDIAAgeIgGgCIgGgBQgHAAgFAFg");
	this.shape_68.setTransform(109.9,65.2);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_69.setTransform(104.3,64.3);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_70.setTransform(98.6,64.3);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AgGAfQgEgFAAgKIAAgcIgGAAIAAgHIAGAAIAAgPIAJAAIAAAPIASAAIAAAHIgSAAIAAAYIAAAIIABAEIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHAAgFgFg");
	this.shape_71.setTransform(93.6,63.6);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgGIgEgCIgGgBQgDAAgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAGIAJgGQAEgCAFAAQAJAAAEAFQAFAGAAAKIAAAig");
	this.shape_72.setTransform(88.4,64.2);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_73.setTransform(82.1,64.3);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("AgEAmIAAhLIAJAAIAABLg");
	this.shape_74.setTransform(77.7,63.2);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFFFF").s().p("AgEAmIAAhLIAJAAIAABLg");
	this.shape_75.setTransform(74.9,63.2);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_76.setTransform(70.5,64.3);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFFFF").s().p("AgXAkIAAhHIAUAAIAKABQAEABAEACQAEADACAEQADAEAAAHQAAAEgCAFQgCAEgDACQgEADgFACQgFACgHAAIgJAAIAAAbgAgNABIAIAAIAIgBQAEAAACgCIAEgFIABgGQAAgEgCgDQgBgDgDgBIgFgCIgHgBIgJAAg");
	this.shape_77.setTransform(64.8,63.4);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AgFAHIAAgNIALAAIAAANg");
	this.shape_78.setTransform(55.9,66.3);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFFFF").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOg");
	this.shape_79.setTransform(50.8,64.3);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_80.setTransform(45.4,64.3);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_81.setTransform(40.1,64.3);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOg");
	this.shape_82.setTransform(34.1,64.3);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFFFFF").s().p("AAfAcIAAgeIgBgHIgBgFIgDgDQgCgBgEAAQgEAAgEACIgIAEIABADIAAADIAAAiIgJAAIAAgeIAAgHIgBgFIgDgDQgCgBgEAAQgEAAgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAGIAJgGQAEgCAFAAQAGAAAEACQACADACAEQAGgFAFgCQAEgCAFAAQAJAAAFAFQAEAGAAAKIAAAig");
	this.shape_83.setTransform(26.4,64.2);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEQgFgCgFAAQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_84.setTransform(243.2,50.1);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#FFFFFF").s().p("AgRAXQgFgFAAgLIAAgiIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIAGABQADAAAEgCIAIgEIAAgoIAJAAIAAA1IgJAAIAAgFIgJAFQgEACgEAAQgJAAgFgFg");
	this.shape_85.setTransform(237.3,50.2);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEQgFgCgFAAQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_86.setTransform(231.5,50.1);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FFFFFF").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAEAAIAEAAIADAAIAAAKIAAAAIgFgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_87.setTransform(227.1,50.1);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FFFFFF").s().p("AgRAXQgFgFAAgLIAAgiIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIAGABQADAAAEgCIAIgEIAAgoIAJAAIAAA1IgJAAIAAgFIgJAFQgEACgEAAQgJAAgFgFg");
	this.shape_88.setTransform(221.2,50.2);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#FFFFFF").s().p("AgFAbQgFgBgEgEQgDgEgCgFQgCgFAAgIQAAgMAHgHQAIgJALAAIAJACIAIADIAAALIAAAAQgFgEgEgCQgFgBgEAAQgHAAgEAFQgFAFAAAJQAAAKAFAGQAEAFAHAAIAGgBIAFgCIAEgCIADgCIAAAAIAAAKIgJADIgIABQgFAAgFgBg");
	this.shape_89.setTransform(215.5,50.1);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEQgFgCgFAAQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_90.setTransform(206.6,50.1);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#FFFFFF").s().p("AgEAkIAAg1IAJAAIAAA1gAgEgaIAAgKIAJAAIAAAKg");
	this.shape_91.setTransform(202.5,49.2);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#FFFFFF").s().p("AgRAXQgFgFAAgLIAAgiIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIAGABQADAAAEgCIAIgEIAAgoIAJAAIAAA1IgJAAIAAgFIgJAFQgEACgEAAQgJAAgFgFg");
	this.shape_92.setTransform(197.8,50.2);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#FFFFFF").s().p("AAOAmIAAgaQgEAEgEACQgEABgEAAQgKAAgFgHQgGgIAAgMQAAgHACgGQACgFADgEQADgDAFgCQAEgCAEAAIAHABIAHADIABgCIAJAAIAABJgAgKgYQgEAGAAAKQAAAIADAFQAEAFAHABQADAAAEgCQAEgCADgDIAAgdIgGgDIgGgBQgHAAgFAFg");
	this.shape_93.setTransform(191.4,51.1);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#FFFFFF").s().p("AgJAQIAIgfIALAAIgMAfg");
	this.shape_94.setTransform(182.9,53.1);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#FFFFFF").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAEAAIAEAAIADAAIAAAKIgBAAIgDgBIgFAAQgEAAgEACIgHAFIAAAlg");
	this.shape_95.setTransform(179.4,50.1);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_96.setTransform(173.6,50.1);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#FFFFFF").s().p("AgEAmIAAhLIAJAAIAABLg");
	this.shape_97.setTransform(169.2,49.1);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_98.setTransform(164.7,50.1);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#FFFFFF").s().p("AgSAfQgFgHAAgOQAAgHACgEQACgFADgEQAEgEAEgCQAFgCADAAIAHABIAHADIAAgYIAKAAIAABLIgKAAIAAgFIgIAFQgEACgEAAQgKAAgGgIgAgKgEQgEAEAAAKQAAAKADAFQAEAFAHAAQADAAAEgCQAEgBADgDIAAgeIgGgDIgGAAQgHAAgFAFg");
	this.shape_99.setTransform(158.3,49.1);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#FFFFFF").s().p("AAfAcIAAgeIgBgHIgBgFIgDgDQgCgCgEAAQgEABgEACIgIAEIABADIAAADIAAAiIgJAAIAAgeIAAgHIgBgFIgDgDQgCgCgEAAQgEABgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAFIAJgFQAEgCAFAAQAGAAAEADQACACACAEQAGgFAFgCQAEgCAFAAQAJAAAFAFQAEAGAAAKIAAAig");
	this.shape_100.setTransform(146.8,50.1);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#FFFFFF").s().p("AgRAXQgFgFAAgLIAAgiIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIAGABQADAAAEgCIAIgEIAAgoIAJAAIAAA1IgJAAIAAgFIgJAFQgEACgEAAQgJAAgFgFg");
	this.shape_101.setTransform(138.7,50.2);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#FFFFFF").s().p("AgGAfQgEgEAAgLIAAgcIgGAAIAAgHIAGAAIAAgQIAJAAIAAAQIASAAIAAAHIgSAAIAAAZIAAAHIABAEIADACIAFABIAFAAIAEgBIAAAAIAAAIIgGABIgFAAQgHABgFgFg");
	this.shape_102.setTransform(133.6,49.4);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#FFFFFF").s().p("AgFAbQgFgBgEgEQgDgEgCgFQgCgFAAgIQAAgMAHgHQAIgJALAAIAJACIAIADIAAALIAAAAQgFgEgEgCQgFgBgEAAQgHAAgEAFQgFAFAAAJQAAAKAFAGQAEAFAHAAIAGgBIAFgCIAEgCIADgCIAAAAIAAAKIgJADIgIABQgFAAgFgBg");
	this.shape_103.setTransform(129,50.1);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#FFFFFF").s().p("AgEAkIAAg1IAJAAIAAA1gAgEgaIAAgKIAJAAIAAAKg");
	this.shape_104.setTransform(124.8,49.2);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#FFFFFF").s().p("AgRAfQgGgHAAgOQAAgHACgEQABgFAEgEQAEgEAEgCQAFgCADAAIAIABIAHADIAAgYIAJAAIAABLIgJAAIAAgFIgIAFQgFACgEAAQgKAAgFgIgAgJgEQgFAEAAAKQAAAKAEAFQADAFAHAAQADAAAEgCQAEgBAEgDIAAgeIgHgDIgHAAQgGAAgEAFg");
	this.shape_105.setTransform(120.1,49.1);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#FFFFFF").s().p("AgGAfQgEgEAAgLIAAgcIgGAAIAAgHIAGAAIAAgQIAJAAIAAAQIASAAIAAAHIgSAAIAAAZIAAAHIABAEIADACIAFABIAFAAIAEgBIAAAAIAAAIIgGABIgFAAQgHABgFgFg");
	this.shape_106.setTransform(111.6,49.4);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#FFFFFF").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOg");
	this.shape_107.setTransform(106.3,50.1);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#FFFFFF").s().p("AgQAbIAAg1IAJAAIAAAIQAGgFADgBQAEgCAFAAIADAAIADAAIAAAKIgBAAIgDgBIgFAAQgEAAgEACIgHAFIAAAlg");
	this.shape_108.setTransform(98.1,50.1);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_109.setTransform(92.4,50.1);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#FFFFFF").s().p("AgKAmIgIgCIAAgJIABAAIAHACQAFABAFAAIAHgBIAEgDIADgFIABgGIAAgFQgFAEgDABQgEACgFAAQgKAAgGgHQgFgHAAgMQAAgHACgFQACgFADgEQADgDAFgCQAEgCAEAAIAIABIAHADIAAgDIAJAAIAAAwQAAANgHAHQgGAGgMAAIgJAAgAgKgYQgEAFAAAKQAAAJAEAEQACAEAIAAIAHgBIAIgEIAAgdIgHgCIgHgBQgGAAgFAFg");
	this.shape_110.setTransform(86.1,51.1);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_111.setTransform(80.1,50.1);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#FFFFFF").s().p("AgGAfQgEgEAAgLIAAgcIgGAAIAAgHIAGAAIAAgQIAJAAIAAAQIASAAIAAAHIgSAAIAAAZIAAAHIABAEIADACIAFABIAFAAIAEgBIAAAAIAAAIIgGABIgFAAQgHABgFgFg");
	this.shape_112.setTransform(75.1,49.4);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgFIgEgDIgGgCQgDABgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAFIAJgFQAEgCAFAAQAJAAAEAFQAFAFAAALIAAAig");
	this.shape_113.setTransform(69.9,50.1);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#FFFFFF").s().p("AgNAkIAAgHIAJAAIAAg5IgJAAIAAgHIAcAAIAAAHIgKAAIAAA5IAKAAIAAAHg");
	this.shape_114.setTransform(64.5,49.2);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#FFFFFF").s().p("AgFAHIAAgNIALAAIAAANg");
	this.shape_115.setTransform(56.9,52.2);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEQgFgCgFAAQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_116.setTransform(52.5,50.1);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#FFFFFF").s().p("AgRAXQgFgFAAgLIAAgiIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIAGABQADAAAEgCIAIgEIAAgoIAJAAIAAA1IgJAAIAAgFIgJAFQgEACgEAAQgJAAgFgFg");
	this.shape_117.setTransform(46.5,50.2);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#FFFFFF").s().p("AgHAmIgHgDIAAACIgJAAIAAhLIAJAAIAAAbIAJgFQAEgCAEAAQAKAAAFAIQAGAHAAANQAAAGgCAGQgCAFgDAEQgDAEgFACQgEACgFAAIgHgBgAgGgHQgFABgDADIAAAeIAHADIAGABQAHAAAFgFQAEgFgBgLQAAgKgCgEQgEgFgHAAQgDAAgEACg");
	this.shape_118.setTransform(40.4,49.1);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#FFFFFF").s().p("AgEAkIAAg1IAJAAIAAA1gAgEgaIAAgKIAJAAIAAAKg");
	this.shape_119.setTransform(35.7,49.2);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgFIgEgDIgGgCQgDABgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAFIAJgFQAEgCAFAAQAJAAAEAFQAFAFAAALIAAAig");
	this.shape_120.setTransform(31.1,50.1);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f("#FFFFFF").s().p("AgEAkIAAg1IAJAAIAAA1gAgEgaIAAgKIAJAAIAAAKg");
	this.shape_121.setTransform(26.5,49.2);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#FFFFFF").s().p("AgLAmIAAguIgFAAIAAgHIAFAAIAAgCQABgKAEgFQAFgFAJAAIAFAAIAFABIAAAIIgBAAIgEgBIgEAAQgHAAgCACQgCADAAAHIAAACIAQAAIAAAHIgQAAIAAAug");
	this.shape_122.setTransform(23.6,49);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_123.setTransform(263.3,36);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_124.setTransform(257.6,36);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.f("#FFFFFF").s().p("AgFAbQgFgBgEgFQgDgDgCgFQgCgGAAgHQAAgMAHgHQAIgJALABIAJABIAIADIAAAKIAAAAQgFgDgEgBQgFgCgEAAQgHgBgEAGQgFAFAAAJQAAAKAFAGQAEAFAHAAIAGgBIAFgCIAEgCIADgCIAAAAIAAAKIgJAEIgIAAQgFABgFgCg");
	this.shape_125.setTransform(252,36);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_126.setTransform(247.9,35.1);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.f("#FFFFFF").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAEAAIAEAAIADAAIAAAKIAAAAIgFgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_127.setTransform(244.8,36);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.f("#FFFFFF").s().p("AgGAfQgEgEAAgLIAAgbIgGAAIAAgIIAGAAIAAgQIAJAAIAAAQIASAAIAAAIIgSAAIAAAYIAAAGIABAFIADACIAFABIAFAAIAEgBIAAAAIAAAIIgGABIgFAAQgHAAgFgEg");
	this.shape_128.setTransform(240.2,35.3);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.f("#FFFFFF").s().p("AgEAmIAAhLIAJAAIAABLg");
	this.shape_129.setTransform(236.7,34.9);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.f("#FFFFFF").s().p("AgRAXQgFgFAAgKIAAgjIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIAGABQADAAAEgCIAIgFIAAgnIAJAAIAAA2IgJAAIAAgHIgJAGQgEACgEAAQgJAAgFgFg");
	this.shape_130.setTransform(232.1,36.1);

	this.shape_131 = new cjs.Shape();
	this.shape_131.graphics.f("#FFFFFF").s().p("AgGAfQgEgEAAgLIAAgbIgGAAIAAgIIAGAAIAAgQIAJAAIAAAQIASAAIAAAIIgSAAIAAAYIAAAGIABAFIADACIAFABIAFAAIAEgBIAAAAIAAAIIgGABIgFAAQgHAAgFgEg");
	this.shape_131.setTransform(223.4,35.3);

	this.shape_132 = new cjs.Shape();
	this.shape_132.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_132.setTransform(218.3,36);

	this.shape_133 = new cjs.Shape();
	this.shape_133.graphics.f("#FFFFFF").s().p("AgKAmIgIgCIAAgJIABAAIAHACIAKABIAGgBIAGgDIACgFIAAgGIAAgFQgDAEgFABQgDACgFAAQgKAAgGgHQgFgHAAgMQAAgHACgFQACgFADgEQADgDAFgCQAFgCADAAIAIABIAGADIABgDIAJAAIAAAwQAAANgHAHQgGAGgMAAIgJAAgAgKgYQgEAFAAAKQAAAJADAEQADAEAIAAIAHgBIAHgEIAAgdIgGgCIgGgBQgHAAgFAFg");
	this.shape_133.setTransform(212,36.9);

	this.shape_134 = new cjs.Shape();
	this.shape_134.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_134.setTransform(205.9,36);

	this.shape_135 = new cjs.Shape();
	this.shape_135.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_135.setTransform(196.2,36);

	this.shape_136 = new cjs.Shape();
	this.shape_136.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_136.setTransform(191.8,35.1);

	this.shape_137 = new cjs.Shape();
	this.shape_137.graphics.f("#FFFFFF").s().p("AgRAfQgGgHAAgOQAAgHACgEQABgFAEgEQAEgEAEgCQAFgCADAAIAIABIAGADIAAgYIAKAAIAABLIgKAAIAAgFIgHAFQgFACgEAAQgKAAgFgIgAgJgEQgFAEAAAKQAAAKAEAFQADAFAHAAQADAAAEgCQAEgBADgDIAAgeIgGgDIgHAAQgGAAgEAFg");
	this.shape_137.setTransform(187.1,35);

	this.shape_138 = new cjs.Shape();
	this.shape_138.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_138.setTransform(181,36);

	this.shape_139 = new cjs.Shape();
	this.shape_139.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_139.setTransform(171.3,36);

	this.shape_140 = new cjs.Shape();
	this.shape_140.graphics.f("#FFFFFF").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAEAAIAEAAIADAAIAAAKIAAAAIgFgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_140.setTransform(166.6,36);

	this.shape_141 = new cjs.Shape();
	this.shape_141.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_141.setTransform(160.9,36);

	this.shape_142 = new cjs.Shape();
	this.shape_142.graphics.f("#FFFFFF").s().p("AgRAXQgFgFAAgKIAAgjIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIAGABQADAAAEgCIAIgFIAAgnIAJAAIAAA2IgJAAIAAgHIgJAGQgEACgEAAQgJAAgFgFg");
	this.shape_142.setTransform(154.6,36.1);

	this.shape_143 = new cjs.Shape();
	this.shape_143.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_143.setTransform(148.9,36);

	this.shape_144 = new cjs.Shape();
	this.shape_144.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_144.setTransform(143.1,36);

	this.shape_145 = new cjs.Shape();
	this.shape_145.graphics.f("#FFFFFF").s().p("AgXAmIAAhKIAJAAIAAAGIAJgFQAEgCAEAAQAKAAAFAHQAGAIAAANQAAAGgCAFQgCAFgDAFQgEADgEACQgEACgFAAIgHgBIgHgDIAAAXgAgGgbIgIAFIAAAeIAHACIAGABQAHAAAEgGQAFgEAAgKQgBgJgDgFQgDgGgHAAQgDAAgEACg");
	this.shape_145.setTransform(137.1,36.9);

	this.shape_146 = new cjs.Shape();
	this.shape_146.graphics.f("#FFFFFF").s().p("AgFAbQgFgBgEgFQgDgDgCgFQgCgGAAgHQAAgMAHgHQAIgJALABIAJABIAIADIAAAKIAAAAQgFgDgEgBQgFgCgEAAQgHgBgEAGQgFAFAAAJQAAAKAFAGQAEAFAHAAIAGgBIAFgCIAEgCIADgCIAAAAIAAAKIgJAEIgIAAQgFABgFgCg");
	this.shape_146.setTransform(127.6,36);

	this.shape_147 = new cjs.Shape();
	this.shape_147.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_147.setTransform(121.8,36);

	this.shape_148 = new cjs.Shape();
	this.shape_148.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgFIgEgEIgGgBQgDAAgEACIgIAFIAAAoIgJAAIAAg2IAJAAIAAAGIAJgFQAEgCAFAAQAJAAAEAGQAFAEAAALIAAAig");
	this.shape_148.setTransform(115.6,35.9);

	this.shape_149 = new cjs.Shape();
	this.shape_149.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_149.setTransform(109.3,36);

	this.shape_150 = new cjs.Shape();
	this.shape_150.graphics.f("#FFFFFF").s().p("AgeAkIAAhHIASAAQALAAAGABIAKAEQAHAFAEAIQAFAHAAAKQAAAKgFAIQgEAIgHAEQgFAEgGABQgFABgLAAgAgUAcIAJAAIALgBQAFgBAEgDQAGgDADgGQADgGAAgIQAAgIgEgGQgCgFgHgEQgDgCgFgBIgLgBIgJAAg");
	this.shape_150.setTransform(102.5,35.1);

	this.shape_151 = new cjs.Shape();
	this.shape_151.graphics.f("#FFFFFF").s().p("AgFAHIAAgNIALAAIAAANg");
	this.shape_151.setTransform(93,38);

	this.shape_152 = new cjs.Shape();
	this.shape_152.graphics.f("#FFFFFF").s().p("AgGAfQgEgEAAgLIAAgbIgGAAIAAgIIAGAAIAAgQIAJAAIAAAQIASAAIAAAIIgSAAIAAAYIAAAGIABAFIADACIAFABIAFAAIAEgBIAAAAIAAAIIgGABIgFAAQgHAAgFgEg");
	this.shape_152.setTransform(89.2,35.3);

	this.shape_153 = new cjs.Shape();
	this.shape_153.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_153.setTransform(85.7,35.1);

	this.shape_154 = new cjs.Shape();
	this.shape_154.graphics.f("#FFFFFF").s().p("AgEAmIAAhLIAJAAIAABLg");
	this.shape_154.setTransform(82.9,34.9);

	this.shape_155 = new cjs.Shape();
	this.shape_155.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_155.setTransform(78.5,36);

	this.shape_156 = new cjs.Shape();
	this.shape_156.graphics.f("#FFFFFF").s().p("AgKAmIgIgCIAAgJIABAAIAHACIAKABIAHgBIAEgDIADgFIABgGIAAgFQgFAEgDABQgEACgFAAQgKAAgGgHQgFgHAAgMQAAgHACgFQACgFADgEQADgDAFgCQAEgCAEAAIAIABIAHADIAAgDIAJAAIAAAwQAAANgHAHQgGAGgMAAIgJAAgAgKgYQgEAFAAAKQAAAJAEAEQACAEAIAAIAHgBIAIgEIAAgdIgHgCIgHgBQgGAAgFAFg");
	this.shape_156.setTransform(68.6,36.9);

	this.shape_157 = new cjs.Shape();
	this.shape_157.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgFIgEgEIgGgBQgDAAgEACIgIAFIAAAoIgJAAIAAg2IAJAAIAAAGIAJgFQAEgCAFAAQAJAAAEAGQAFAEAAALIAAAig");
	this.shape_157.setTransform(62.4,35.9);

	this.shape_158 = new cjs.Shape();
	this.shape_158.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_158.setTransform(57.8,35.1);

	this.shape_159 = new cjs.Shape();
	this.shape_159.graphics.f("#FFFFFF").s().p("AgFAbQgFgBgEgFQgDgDgCgFQgCgGAAgHQAAgMAHgHQAIgJALABIAJABIAIADIAAAKIAAAAQgFgDgEgBQgFgCgEAAQgHgBgEAGQgFAFAAAJQAAAKAFAGQAEAFAHAAIAGgBIAFgCIAEgCIADgCIAAAAIAAAKIgJAEIgIAAQgFABgFgCg");
	this.shape_159.setTransform(53.8,36);

	this.shape_160 = new cjs.Shape();
	this.shape_160.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_160.setTransform(48.5,36);

	this.shape_161 = new cjs.Shape();
	this.shape_161.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_161.setTransform(44.4,35.1);

	this.shape_162 = new cjs.Shape();
	this.shape_162.graphics.f("#FFFFFF").s().p("AgXAmIAAhKIAJAAIAAAGIAIgFQAFgCAEAAQAKAAAFAHQAGAIAAANQAAAGgCAFQgCAFgDAFQgDADgFACQgEACgFAAIgHgBIgHgDIAAAXgAgGgbIgIAFIAAAeIAHACIAHABQAGAAAEgGQAEgEABgKQAAgJgEgFQgDgGgHAAQgDAAgEACg");
	this.shape_162.setTransform(40,36.9);

	this.shape_163 = new cjs.Shape();
	this.shape_163.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_163.setTransform(35.3,35.1);

	this.shape_164 = new cjs.Shape();
	this.shape_164.graphics.f("#FFFFFF").s().p("AgRAfQgGgHAAgOQAAgHACgEQABgFAEgEQAEgEAEgCQAFgCADAAIAIABIAHADIAAgYIAJAAIAABLIgJAAIAAgFIgIAFQgFACgEAAQgKAAgFgIgAgJgEQgFAEAAAKQAAAKAEAFQADAFAHAAQADAAAEgCQAEgBAEgDIAAgeIgHgDIgHAAQgGAAgEAFg");
	this.shape_164.setTransform(30.6,35);

	this.shape_165 = new cjs.Shape();
	this.shape_165.graphics.f("#FFFFFF").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOg");
	this.shape_165.setTransform(24.3,36);

	this.shape_166 = new cjs.Shape();
	this.shape_166.graphics.f("#FFFFFF").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAFAAIADAAIADAAIAAAKIgBAAIgDgBIgFAAQgEAAgEACIgHAFIAAAlg");
	this.shape_166.setTransform(227.2,21.8);

	this.shape_167 = new cjs.Shape();
	this.shape_167.graphics.f("#FFFFFF").s().p("AgRAXQgFgGAAgJIAAgjIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAABIAGABQADgBAEgBIAIgGIAAgnIAJAAIAAA2IgJAAIAAgHIgJAGQgEACgEAAQgJAAgFgFg");
	this.shape_167.setTransform(221.3,21.9);

	this.shape_168 = new cjs.Shape();
	this.shape_168.graphics.f("#FFFFFF").s().p("AgGAfQgEgEAAgKIAAgcIgGAAIAAgIIAGAAIAAgQIAJAAIAAAQIASAAIAAAIIgSAAIAAAXIAAAHIABAFIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHgBgFgEg");
	this.shape_168.setTransform(216.2,21.1);

	this.shape_169 = new cjs.Shape();
	this.shape_169.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_169.setTransform(211.1,21.8);

	this.shape_170 = new cjs.Shape();
	this.shape_170.graphics.f("#FFFFFF").s().p("AgGAfQgEgEAAgKIAAgcIgGAAIAAgIIAGAAIAAgQIAJAAIAAAQIASAAIAAAIIgSAAIAAAXIAAAHIABAFIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHgBgFgEg");
	this.shape_170.setTransform(206.1,21.1);

	this.shape_171 = new cjs.Shape();
	this.shape_171.graphics.f("#FFFFFF").s().p("AgFAbQgFgCgEgEQgDgDgCgFQgCgGAAgGQAAgNAHgIQAIgHALAAIAJABIAIADIAAAKIAAAAQgFgDgEgBQgFgCgEgBQgHAAgEAGQgFAFAAAKQAAAJAFAFQAEAGAHAAIAGgBIAFgCIAEgCIADgCIAAAAIAAAKIgJAEIgIABQgFgBgFgBg");
	this.shape_171.setTransform(201.5,21.8);

	this.shape_172 = new cjs.Shape();
	this.shape_172.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_172.setTransform(195.7,21.8);

	this.shape_173 = new cjs.Shape();
	this.shape_173.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_173.setTransform(190.1,21.8);

	this.shape_174 = new cjs.Shape();
	this.shape_174.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgGIgEgDIgGgBQgDAAgEACIgIAGIAAAnIgJAAIAAg2IAJAAIAAAHIAJgGQAEgCAFAAQAJAAAEAGQAFAFAAAJIAAAjg");
	this.shape_174.setTransform(184.2,21.8);

	this.shape_175 = new cjs.Shape();
	this.shape_175.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_175.setTransform(177.9,21.8);

	this.shape_176 = new cjs.Shape();
	this.shape_176.graphics.f("#FFFFFF").s().p("AgFAbQgFgCgEgEQgDgDgCgFQgCgGAAgGQAAgNAHgIQAIgHALAAIAJABIAIADIAAAKIAAAAQgFgDgEgBQgFgCgEgBQgHAAgEAGQgFAFAAAKQAAAJAFAFQAEAGAHAAIAGgBIAFgCIAEgCIADgCIAAAAIAAAKIgJAEIgIABQgFgBgFgBg");
	this.shape_176.setTransform(172.3,21.8);

	this.shape_177 = new cjs.Shape();
	this.shape_177.graphics.f("#FFFFFF").s().p("AgKAQIAJgfIALAAIgMAfg");
	this.shape_177.setTransform(164.1,24.8);

	this.shape_178 = new cjs.Shape();
	this.shape_178.graphics.f("#FFFFFF").s().p("AgGAfQgEgEAAgKIAAgcIgGAAIAAgIIAGAAIAAgQIAJAAIAAAQIASAAIAAAIIgSAAIAAAXIAAAHIABAFIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHgBgFgEg");
	this.shape_178.setTransform(160.3,21.1);

	this.shape_179 = new cjs.Shape();
	this.shape_179.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_179.setTransform(155.2,21.8);

	this.shape_180 = new cjs.Shape();
	this.shape_180.graphics.f("#FFFFFF").s().p("AAfAcIAAgeIgBgHIgBgFIgDgDQgCgBgEgBQgEAAgEACIgIAGIABACIAAADIAAAiIgJAAIAAgeIAAgHIgBgFIgDgDQgCgBgEgBQgEAAgEACIgIAGIAAAnIgJAAIAAg2IAJAAIAAAHIAJgGQAEgCAFAAQAGAAAEACQACACACAFQAGgFAFgCQAEgCAFAAQAJAAAFAGQAEAFAAAJIAAAjg");
	this.shape_180.setTransform(147.3,21.8);

	this.shape_181 = new cjs.Shape();
	this.shape_181.graphics.f("#FFFFFF").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOg");
	this.shape_181.setTransform(139.2,21.8);

	this.shape_182 = new cjs.Shape();
	this.shape_182.graphics.f("#FFFFFF").s().p("AgGAfQgEgEAAgKIAAgcIgGAAIAAgIIAGAAIAAgQIAJAAIAAAQIASAAIAAAIIgSAAIAAAXIAAAHIABAFIADADIAFABIAFgBIAEgBIAAAAIAAAIIgGABIgFABQgHgBgFgEg");
	this.shape_182.setTransform(130.8,21.1);

	this.shape_183 = new cjs.Shape();
	this.shape_183.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_183.setTransform(127.3,20.9);

	this.shape_184 = new cjs.Shape();
	this.shape_184.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_184.setTransform(123.3,21.8);

	this.shape_185 = new cjs.Shape();
	this.shape_185.graphics.f("#FFFFFF").s().p("AgQAbIAAg1IAJAAIAAAIQAGgFADgBQAEgCAFAAIADAAIADAAIAAAKIgBAAIgEgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_185.setTransform(115.3,21.8);

	this.shape_186 = new cjs.Shape();
	this.shape_186.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_186.setTransform(109.6,21.8);

	this.shape_187 = new cjs.Shape();
	this.shape_187.graphics.f("#FFFFFF").s().p("AgEAmIAAhLIAJAAIAABLg");
	this.shape_187.setTransform(105.1,20.8);

	this.shape_188 = new cjs.Shape();
	this.shape_188.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_188.setTransform(100.6,21.8);

	this.shape_189 = new cjs.Shape();
	this.shape_189.graphics.f("#FFFFFF").s().p("AgRAfQgGgHAAgOQAAgHACgEQACgFADgEQAEgEAEgCQAFgCADAAIAIABIAGADIAAgYIAKAAIAABLIgKAAIAAgFIgIAFQgEACgEAAQgKAAgFgIgAgJgEQgFAEAAAKQAAAKADAFQAEAFAHAAQADAAAEgCQAEgBADgDIAAgeIgGgDIgGAAQgHAAgEAFg");
	this.shape_189.setTransform(94.3,20.8);

	this.shape_190 = new cjs.Shape();
	this.shape_190.graphics.f("#FFFFFF").s().p("AAfAcIAAgeIgBgHIgBgFIgDgDQgCgBgEgBQgEAAgEACIgIAGIABACIAAADIAAAiIgJAAIAAgeIAAgHIgBgFIgDgDQgCgBgEgBQgEAAgEACIgIAGIAAAnIgJAAIAAg2IAJAAIAAAHIAJgGQAEgCAFAAQAGAAAEACQACACACAFQAGgFAFgCQAEgCAFAAQAJAAAFAGQAEAFAAAJIAAAjg");
	this.shape_190.setTransform(82.8,21.8);

	this.shape_191 = new cjs.Shape();
	this.shape_191.graphics.f("#FFFFFF").s().p("AgRAXQgFgGAAgJIAAgjIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAABIAGABQADgBAEgBIAIgGIAAgnIAJAAIAAA2IgJAAIAAgHIgJAGQgEACgEAAQgJAAgFgFg");
	this.shape_191.setTransform(74.6,21.9);

	this.shape_192 = new cjs.Shape();
	this.shape_192.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_192.setTransform(68.9,21.8);

	this.shape_193 = new cjs.Shape();
	this.shape_193.graphics.f("#FFFFFF").s().p("AgXAmIAAhKIAJAAIAAAGIAIgFQAFgCAEAAQAKAAAGAIQAFAHAAANQAAAHgCAEQgCAFgDAFQgDADgFACQgEACgFAAIgHgBIgHgDIAAAXgAgGgbIgIAFIAAAeIAHACIAHABQAGAAAFgFQADgFAAgKQABgKgEgEQgDgGgHAAQgDAAgEACg");
	this.shape_193.setTransform(63.2,22.8);

	this.shape_194 = new cjs.Shape();
	this.shape_194.graphics.f("#FFFFFF").s().p("AgEAlIAAg2IAJAAIAAA2gAgEgaIAAgJIAJAAIAAAJg");
	this.shape_194.setTransform(58.5,20.9);

	this.shape_195 = new cjs.Shape();
	this.shape_195.graphics.f("#FFFFFF").s().p("AAfAcIAAgeIgBgHIgBgFIgDgDQgCgBgEgBQgEAAgEACIgIAGIABACIAAADIAAAiIgJAAIAAgeIAAgHIgBgFIgDgDQgCgBgEgBQgEAAgEACIgIAGIAAAnIgJAAIAAg2IAJAAIAAAHIAJgGQAEgCAFAAQAGAAAEACQACACACAFQAGgFAFgCQAEgCAFAAQAJAAAFAGQAEAFAAAJIAAAjg");
	this.shape_195.setTransform(48.6,21.8);

	this.shape_196 = new cjs.Shape();
	this.shape_196.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_196.setTransform(40.6,21.8);

	this.shape_197 = new cjs.Shape();
	this.shape_197.graphics.f("#FFFFFF").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAFAAIADAAIADAAIAAAKIgBAAIgDgBIgFAAQgEAAgEACIgHAFIAAAlg");
	this.shape_197.setTransform(35.9,21.8);

	this.shape_198 = new cjs.Shape();
	this.shape_198.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_198.setTransform(30.2,21.8);

	this.shape_199 = new cjs.Shape();
	this.shape_199.graphics.f("#FFFFFF").s().p("AgWAkIAAhHIAKAAIAAA/IAjAAIAAAIg");
	this.shape_199.setTransform(24.8,20.9);

	this.shape_200 = new cjs.Shape();
	this.shape_200.graphics.f("rgba(58,59,62,0.847)").s().p("A3bH0IAAvnMAu3AAAIAAPng");
	this.shape_200.setTransform(150,50);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_200},{t:this.shape_199},{t:this.shape_198},{t:this.shape_197},{t:this.shape_196},{t:this.shape_195},{t:this.shape_194},{t:this.shape_193},{t:this.shape_192},{t:this.shape_191},{t:this.shape_190},{t:this.shape_189},{t:this.shape_188},{t:this.shape_187},{t:this.shape_186},{t:this.shape_185},{t:this.shape_184},{t:this.shape_183},{t:this.shape_182},{t:this.shape_181},{t:this.shape_180},{t:this.shape_179},{t:this.shape_178},{t:this.shape_177},{t:this.shape_176},{t:this.shape_175},{t:this.shape_174},{t:this.shape_173},{t:this.shape_172},{t:this.shape_171},{t:this.shape_170},{t:this.shape_169},{t:this.shape_168},{t:this.shape_167},{t:this.shape_166},{t:this.shape_165},{t:this.shape_164},{t:this.shape_163},{t:this.shape_162},{t:this.shape_161},{t:this.shape_160},{t:this.shape_159},{t:this.shape_158},{t:this.shape_157},{t:this.shape_156},{t:this.shape_155},{t:this.shape_154},{t:this.shape_153},{t:this.shape_152},{t:this.shape_151},{t:this.shape_150},{t:this.shape_149},{t:this.shape_148},{t:this.shape_147},{t:this.shape_146},{t:this.shape_145},{t:this.shape_144},{t:this.shape_143},{t:this.shape_142},{t:this.shape_141},{t:this.shape_140},{t:this.shape_139},{t:this.shape_138},{t:this.shape_137},{t:this.shape_136},{t:this.shape_135},{t:this.shape_134},{t:this.shape_133},{t:this.shape_132},{t:this.shape_131},{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tnc2_sub, new cjs.Rectangle(0,0,300,100), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#9933FF").s().p("Ag0BQIAAgcIAhAAIAAhTIghAAIAAgaIAOgBQAIgBAEgCQAGgDACgEQAEgFAAgGIAjAAIAACDIAgAAIAAAcg");
	this.shape.setTransform(207.9,23.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#9933FF").s().p("AgrAwQgUgRAAgeQAAgdATgRQASgSAfAAQAdAAAPAPQAPAPAAAcIAAANIhYAAQABAOAKAHQAKAIASAAQANAAALgFQAMgEAGgFIAFAAIAAAfQgOAFgLADQgMACgOAAQgjAAgTgQgAAZgOQAAgMgGgGQgFgGgMAAQgLAAgHAFQgHAGgBANIAxAAIAAAAg");
	this.shape_1.setTransform(184.9,25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#9933FF").s().p("AgSBUIAAinIAlAAIAACng");
	this.shape_2.setTransform(173.9,22.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#9933FF").s().p("Ag+BUIAAikIAnAAIAAANQAJgHAJgFQAIgEAMAAQAXAAAMAQQANARAAAdQAAAPgFALQgEAMgIAIQgHAJgKAEQgKAEgLAAQgJAAgHgCQgIgCgHgEIAAAygAgMg0QgGABgFAEIAAA7IAIACIAJABQAOAAAIgJQAHgIAAgSQAAgSgGgIQgGgIgMAAIgLACg");
	this.shape_3.setTransform(162.9,27.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#9933FF").s().p("AA8A+IAAg9IgBgNIgCgKQgCgEgEgCQgEgCgHABQgFgBgEACIgMAGIAABUIglAAIAAg9IgBgNQAAgGgCgEQgCgEgEgCQgEgCgHABQgGAAgFABIgKAGIAABUIgnAAIAAh3IAnAAIAAAMQAKgHAJgEQAJgFAMAAQALAAAIAGQAKAEAFALQALgKALgFQALgGALAAQATAAAKAMQALALAAAWIAABOg");
	this.shape_4.setTransform(143.2,24.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#9933FF").s().p("AgvA1QgMgLAAgQQAAgNAGgJQAGgHALgFQAKgEAQgDIAggDIAAAAQAAgLgIgDQgIgEgPAAQgKAAgKADIgQAGIgDAAIAAgeIATgEQAOgBAOAAQAggBAPALQAOAKAAAVIAABSIgmAAIAAgOIgIAHIgIAEQgGAEgFABIgOABQgRAAgLgLgAAFAFIgNAEQgGABgDADQgDAEAAAFIABAHIADAFIAGADIAKAAQAGAAAGgCQAGgCAEgEIAAgZg");
	this.shape_5.setTransform(123.8,25.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#9933FF").s().p("AAaA8IgagkIgaAkIgsAAIAwg8Igvg7IAtAAIAYAjIAagjIAsAAIgvA7IAwA8g");
	this.shape_6.setTransform(109.5,25.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#9933FF").s().p("Ag5BQIAAifIBzAAIAAAfIhKAAIAAAcIBEAAIAAAdIhEAAIAAAoIBKAAIAAAfg");
	this.shape_7.setTransform(95,23.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#9933FF").s().p("AgnBSIATgtIgwh2IApAAIAcBNIAbhNIApAAIhECjg");
	this.shape_8.setTransform(72.5,27.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#9933FF").s().p("Ag+BUIAAikIAnAAIAAANQAJgHAJgFQAIgEAMAAQAXAAAMAQQANARAAAdQAAAPgFALQgEAMgIAIQgHAJgKAEQgKAEgLAAQgJAAgHgCQgIgCgHgEIAAAygAgMg0QgGABgFAEIAAA7IAIACIAJABQAOAAAIgJQAHgIAAgSQAAgSgGgIQgGgIgMAAIgLACg");
	this.shape_9.setTransform(58.1,27.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#9933FF").s().p("AgvAvQgSgRAAgeQAAgdASgRQARgRAeAAQAgAAARARQARARAAAdQAAAegRARQgRARggAAQgfAAgQgRgAgJgjQgFACgDAEQgEAFgCAHQgCAHAAAKQAAAKACAHQABAIAEAEQAEAEAEACQAFACAFAAQAGAAAEgCQAFgBADgFQAFgEABgHQACgGAAgMQAAgJgCgIQgCgHgEgEQgCgFgGgBQgFgCgFAAQgFAAgEABg");
	this.shape_10.setTransform(42.5,25.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#9933FF").s().p("AgTBOQgQgGgKgKQgLgKgGgQQgGgPAAgVQAAgSAGgQQAFgPALgLQAKgLAQgFQAPgGASAAIASABIAPADIANAFIAKAEIAAAnIgFAAIgHgGIgLgHIgMgGQgHgCgIAAQgJAAgIADQgGACgHAHQgGAGgEAKQgEAKAAANQAAAPAEAKQAEALAHAFQAGAGAHADQAIACAIAAQAIAAAHgCIAOgGIAJgHIAIgGIAEAAIAAAnIgLAEIgMAFIgPADIgTABQgQAAgPgFg");
	this.shape_11.setTransform(27,23.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(17,7,200.5,30.7), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABfBeQgLgLAAgSQAAgTALgKQALgMASAAQATAAALAMQALAKAAATQAAASgLALQgLALgTAAQgSAAgLgLgAB1AoQgDACgDADIgEAIQgCAFAAAHQAAAHACAFQABAFADADQADADADACQADABAEAAQAEAAAEgBQADgCADgEQADgDABgFQACgEAAgHQAAgHgCgFIgEgIQgDgDgDgCQgEgBgEAAIgHABgAAJBfQgLgLAAgTQAAgSALgLQALgMAVAAQAHAAAHACQAHABAJAEIAAASIgDAAIgJgGIgHgDIgJgBQgFAAgFABQgEACgDAEQgEACgCAGQgCAEAAAHQAAANAHAGQAHAHANAAIAFAAIAAgQIgPAAIAAgOIAkAAIAAAnIgOADQgIACgJAAQgUABgLgLgAhSBeQgLgLAAgSQAAgTALgKQALgMATAAQASAAALAMQALAKAAATQAAASgLALQgLALgSAAQgTAAgLgLgAg8AoIgGAFIgEAIQgCAFAAAHQAAAHACAFIAEAIQADADADACQAEABAEAAQAEAAADgBQADgCADgEQADgDABgFQACgEAAgHQAAgHgCgFQgBgFgDgDQgDgDgDgCIgHgBQgEAAgEABgAicBoIAAhOIAUAAIAAA/IAkAAIAAAPgAgBgZQgHgCgHgDIAAgTIADAAQAGAFAHADQAHADAHAAIAFgBIAFgBIAEgCQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBgBAAQgCgCgEgBIgJgCIgKgDQgIgDgFgGQgEgFAAgIQAAgLAKgGQAIgIAQAAIAPACIANAEIAAASIgCAAQgFgEgHgCQgHgDgHAAIgFAAIgEACIgEACIgBADQAAAEACACQACABAHABIARAFQAIACAFAGQAEAFAAAHQAAAMgKAHQgJAHgRAAQgKAAgGgBgABRgZIAAg/IgYAAIAAgPIBFAAIAAAPIgZAAIAAA/gAhTgZIAAhOIA4AAIAAAPIgkAAIAAANIAhAAIAAAPIghAAIAAAUIAkAAIAAAPgAiMgZIAAg/IgYAAIAAgPIBFAAIAAAPIgZAAIAAA/g");
	this.shape.setTransform(16.5,10.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(0,0,33,21.1), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// top
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000099").s().p("AgtAaIA/gaIg/gZIAAgUIBbAmIAAAPIhbAmg");
	this.shape.setTransform(114.3,15.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000099").s().p("AAOAnIAAgmIgBgIIgBgHIgEgDIgHgBIgGABIgIADIAAA1IgZAAIAAhLIAZAAIAAAIQAHgFAGgCQAFgDAHAAQAMgBAIAIQAGAHABAPIAAAwg");
	this.shape_1.setTransform(93.7,16.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000099").s().p("AgeAeQgLgLAAgTQAAgSALgLQALgLATAAQAUAAALALQALALAAASQAAATgLALQgLALgUAAQgTAAgLgLgAgFgWQgDABgDADQgCADgBAEQgCAFABAGIAAALQACAFACACQADADACABIAHABIAFgBQADgBADgCIADgHIACgMIgCgKIgDgIQgCgCgEgCIgGgBIgFABg");
	this.shape_2.setTransform(83.9,16.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000099").s().p("AgLAsQgHgFAAgOIAAgjIgKAAIAAgRIAKAAIAAgWIAYAAIAAAWIAXAAIAAARIgXAAIAAAaIAAAGIABAGIADAEQADACAFAAIAFgBIAEgCIACAAIAAARIgIABIgLABQgOAAgHgGg");
	this.shape_3.setTransform(75.9,15.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000099").s().p("AgLAsQgHgFAAgOIAAgjIgKAAIAAgRIAKAAIAAgWIAYAAIAAAWIAXAAIAAARIgXAAIAAAaIAAAGIABAGIADAEQADACAFAAIAFgBIAEgCIACAAIAAARIgIABIgLABQgOAAgHgGg");
	this.shape_4.setTransform(69.6,15.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000099").s().p("AgfAhQgGgIgBgPIAAgwIAZAAIAAAmIAAAIIACAHQACADADAAIAGABIAGgBQAFAAADgDIAAg1IAZAAIAABLIgZAAIAAgIIgMAIQgFADgIAAQgNgBgHgGg");
	this.shape_5.setTransform(61.4,16.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000099").s().p("AgFA0QgFgBgEgCIgBADIgYAAIAAhpIAZAAIAAAmQAGgFAFgCQAGgDAHAAQAPgBAHALQAIALAAARQAAASgKALQgKAMgPAAQgFAAgFgCgAgHgFIgHACIAAAmIAFABIAFABQAKAAAEgGQAFgGAAgMQAAgKgDgEQgEgGgIABIgHABg");
	this.shape_6.setTransform(51.9,14.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000099").s().p("AAaAzIgHgUIglAAIgHAUIgbAAIAmhlIAdAAIAmBlgAAMAMIgMgkIgMAkIAYAAg");
	this.shape_7.setTransform(36.5,15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000099").s().p("AgMAzIAAhRIggAAIAAgUIBZAAIAAAUIggAAIAABRg");
	this.shape_8.setTransform(26.4,15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000099").s().p("AgMAyQgKgEgGgGQgIgHgDgKQgEgKAAgNQAAgLADgJQAFgLAGgGQAHgIAJgDQAKgEALAAIALABIAKACIAIADIAHACIAAAaIgDAAIgFgEIgHgFIgIgDQgEgCgFAAQgGAAgFACQgEACgEADQgDAFgDAFQgCAHgBAIQABAKACAGQACAGAFAEQAEAEAEACQAFACAFAAQAFgBAEgBIAJgEIAGgEIAGgEIACAAIAAAYIgIADIgHADIgJACIgMABQgLAAgJgDg");
	this.shape_9.setTransform(16.6,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// white
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AqYCWIAAkrIUxAAIAAErg");
	this.shape_10.setTransform(66.5,15);

	this.timeline.addTween(cjs.Tween.get(this.shape_10).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(0,0,133,30), null);


(lib.bg_white = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg_white, new cjs.Rectangle(0,0,300,250), null);


(lib.bg_ani = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bg.jpg
	this.instance = new lib.bg();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg_ani, new cjs.Rectangle(0,0,300,250), null);


(lib.tnc2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{open:0});

	// timeline functions:
	this.frame_5 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(5).call(this.frame_5).wait(3));

	// Layer_1
	this.instance = new lib.tnc2_sub();
	this.instance.parent = this;
	this.instance.setTransform(0,260);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:150},5,cjs.Ease.quadOut).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,260,300,100);


(lib.tnc_hitbox = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.tnc2();
	this.instance.parent = this;

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#009900").s().p("AvnBkIAAjHIfPAAIAADHg");
	this.shape.setTransform(120,240);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},1).to({state:[{t:this.shape}]},2).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgFAHIAAgNIALAAIAAANg");
	this.shape_1.setTransform(214.8,245.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEQgFgCgFAAQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_2.setTransform(210.3,243.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgFIgEgDIgGgCQgDABgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAFIAJgFQAEgCAFAAQAJAAAEAFQAFAFAAALIAAAig");
	this.shape_3.setTransform(204.4,243.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_4.setTransform(198.1,243.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgEAkIAAg1IAJAAIAAA1gAgEgaIAAgKIAJAAIAAAKg");
	this.shape_5.setTransform(193.7,242.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGAfQgEgEAAgLIAAgcIgGAAIAAgHIAGAAIAAgQIAJAAIAAAQIASAAIAAAHIgSAAIAAAZIAAAHIABAEIADACIAFABIAFAAIAEgBIAAAAIAAAIIgGABIgFAAQgHABgFgFg");
	this.shape_6.setTransform(190.3,242.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgEAkIAAg1IAJAAIAAA1gAgEgaIAAgKIAJAAIAAAKg");
	this.shape_7.setTransform(186.9,242.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgSAfQgFgHAAgOQAAgHACgEQACgFADgEQAEgEAEgCQAFgCADAAIAHABIAHADIAAgYIAKAAIAABLIgKAAIAAgFIgIAFQgEACgEAAQgKAAgGgIgAgKgEQgEAEAAAKQAAAKADAFQAEAFAHAAQADAAAEgCQAEgBADgDIAAgeIgGgDIgGAAQgHAAgFAFg");
	this.shape_8.setTransform(182.2,242.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgFIgEgDIgGgCQgDABgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAFIAJgFQAEgCAFAAQAJAAAEAFQAFAFAAALIAAAig");
	this.shape_9.setTransform(176,243.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_10.setTransform(169.7,243.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIAjQgGgCgFgFQgFgEgCgHQgDgIAAgJQAAgIACgHQADgHAFgFQAEgFAHgCQAHgDAHAAIALACQAGABAHAEIAAALIgBAAQgGgFgFgCQgGgDgHAAQgFAAgEACQgEACgEAEQgDADgCAGQgCAGAAAGQAAAIACAFQACAGADADQAEAEAEACQAEABAFAAQAHAAAGgCQAGgDAFgEIABAAIAAALIgFACIgFACIgHACIgIABQgGAAgHgDg");
	this.shape_11.setTransform(163.2,242.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgRAfQgGgHAAgOQAAgHACgEQACgFADgEQADgEAFgCQAEgCAEAAIAHABIAHADIAAgYIAKAAIAABLIgKAAIAAgFIgIAFQgEACgEAAQgKAAgFgIgAgKgEQgEAEAAAKQAAAKADAFQAEAFAHAAQADAAAEgCQAEgBADgDIAAgeIgGgDIgGAAQgHAAgFAFg");
	this.shape_12.setTransform(152.7,242.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAOAcIAAgeIgBgHIgBgFIgEgDIgGgCQgDABgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAFIAJgFQAEgCAFAAQAJAAAEAFQAFAFAAALIAAAig");
	this.shape_13.setTransform(146.5,243.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOg");
	this.shape_14.setTransform(140,243.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEQgFgCgFAAQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_15.setTransform(131,243.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAfAcIAAgeIgBgHIgBgFIgDgDQgCgCgEAAQgEABgEACIgIAEIABADIAAADIAAAiIgJAAIAAgeIAAgHIgBgFIgDgDQgCgCgEAAQgEABgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAFIAJgFQAEgCAFAAQAGAAAEADQACACACAEQAGgFAFgCQAEgCAFAAQAJAAAFAFQAEAGAAAKIAAAig");
	this.shape_16.setTransform(123.4,243.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgQAbIAAg1IAJAAIAAAIQAGgFADgBQAEgCAFAAIADAAIADAAIAAAKIAAAAIgFgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_17.setTransform(116.8,243.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_18.setTransform(111.1,243.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgEAkIAAg/IgaAAIAAgIIA9AAIAAAIIgaAAIAAA/g");
	this.shape_19.setTransform(104.9,242.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgQAbIAAg1IAJAAIAAAIQAGgFADgBQAEgCAFAAIADAAIADAAIAAAKIAAAAIgFgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_20.setTransform(96.5,243.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_21.setTransform(90.8,243.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgKAmIAAguIgGAAIAAgHIAGAAIAAgCQAAgKAEgFQAFgFAJAAIAFAAIAFABIAAAIIgBAAIgEgBIgEAAQgGAAgDACQgBADAAAHIAAACIAPAAIAAAHIgPAAIAAAug");
	this.shape_22.setTransform(86.3,242.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAEAAIAEAAIADAAIAAAKIAAAAIgFgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_23.setTransform(78.8,243.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_24.setTransform(73.1,243.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgDAbIgXg1IAKAAIAQAqIARgqIAKAAIgWA1g");
	this.shape_25.setTransform(67.1,243.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_26.setTransform(61,243.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_27.setTransform(51.3,243.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEQgFgCgFAAQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_28.setTransform(45.7,243.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgRAXQgFgFAAgLIAAgiIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIAGABQADAAAEgCIAIgEIAAgoIAJAAIAAA1IgJAAIAAgFIgJAFQgEACgEAAQgJAAgFgFg");
	this.shape_29.setTransform(39.8,243.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_30.setTransform(33.5,243.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAXAkIAAg9IgVApIgEAAIgUgpIAAA9IgJAAIAAhHIANAAIASAnIATgnIANAAIAABHg");
	this.shape_31.setTransform(26.2,242.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgFAHIAAgNIALAAIAAANg");
	this.shape_32.setTransform(215.8,246.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_33.setTransform(211.3,244.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAOAcIAAgeIgBgHIgBgFIgEgDIgGgBQgDAAgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAFIAJgFQAEgCAFAAQAJAAAEAFQAFAGAAAKIAAAig");
	this.shape_34.setTransform(205.4,244.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_35.setTransform(199.1,244.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgEAkIAAg1IAJAAIAAA1gAgEgaIAAgKIAJAAIAAAKg");
	this.shape_36.setTransform(194.7,243.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgGAfQgEgEAAgLIAAgcIgGAAIAAgHIAGAAIAAgPIAJAAIAAAPIASAAIAAAHIgSAAIAAAZIAAAHIABAEIADACIAFACIAFgBIAEgBIAAAAIAAAIIgGABIgFAAQgHABgFgFg");
	this.shape_37.setTransform(191.3,243.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgEAkIAAg1IAJAAIAAA1gAgEgaIAAgKIAJAAIAAAKg");
	this.shape_38.setTransform(187.9,243.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgSAfQgFgHAAgOQAAgHACgEQACgFADgEQAEgEAEgCQAEgCAEAAIAHABIAHADIAAgYIAKAAIAABLIgKAAIAAgFIgIAFQgEACgEAAQgKAAgGgIgAgKgEQgEAEAAAKQAAAKADAFQAEAFAHAAQADAAAEgCQAEgBADgDIAAgeIgGgDIgGAAQgHAAgFAFg");
	this.shape_39.setTransform(183.2,243.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAOAcIAAgeIgBgHIgBgFIgEgDIgGgBQgDAAgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAFIAJgFQAEgCAFAAQAJAAAEAFQAFAGAAAKIAAAig");
	this.shape_40.setTransform(177,244.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_41.setTransform(170.7,244.2);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgIAjQgGgCgFgFQgFgEgCgHQgDgIAAgJQAAgIACgHQADgHAFgFQAEgFAHgCQAHgDAHAAIALACQAGABAHAEIAAALIgBAAQgGgFgFgCQgGgDgHAAQgFAAgEACQgEACgEAEQgDADgCAGQgCAGAAAGQAAAIACAFQACAGADADQAEAEAEACQAEABAFAAQAHAAAGgCQAGgDAFgEIABAAIAAALIgFACIgFACIgHACIgIABQgGAAgHgDg");
	this.shape_42.setTransform(164.2,243.3);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgRAfQgGgHAAgOQAAgHACgEQACgFADgEQAEgEAEgCQAFgCADAAIAIABIAGADIAAgYIAKAAIAABLIgKAAIAAgFIgIAFQgEACgEAAQgKAAgFgIgAgJgEQgFAEAAAKQAAAKADAFQAEAFAHAAQADAAAEgCQAEgBADgDIAAgeIgGgDIgGAAQgHAAgEAFg");
	this.shape_43.setTransform(153.7,243.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AAOAcIAAgeIgBgHIgBgFIgEgDIgGgBQgDAAgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAFIAJgFQAEgCAFAAQAJAAAEAFQAFAGAAAKIAAAig");
	this.shape_44.setTransform(147.5,244.1);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOg");
	this.shape_45.setTransform(141,244.2);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_46.setTransform(132,244.2);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AAfAcIAAgeIgBgHIgBgFIgDgDQgCgBgEAAQgEAAgEACIgIAEIABADIAAADIAAAiIgJAAIAAgeIAAgHIgBgFIgDgDQgCgBgEAAQgEAAgEACIgIAEIAAAoIgJAAIAAg1IAJAAIAAAFIAJgFQAEgCAFAAQAGAAAEADQACACACAEQAGgFAFgCQAEgCAFAAQAJAAAFAFQAEAGAAAKIAAAig");
	this.shape_47.setTransform(124.4,244.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAEAAIAEAAIADAAIAAAKIAAAAIgFgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_48.setTransform(117.8,244.2);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_49.setTransform(112.1,244.2);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgEAkIAAg/IgaAAIAAgIIA9AAIAAAIIgaAAIAAA/g");
	this.shape_50.setTransform(105.9,243.3);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAEAAIAEAAIADAAIAAAKIAAAAIgFgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_51.setTransform(97.5,244.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_52.setTransform(91.8,244.2);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AgKAmIAAguIgHAAIAAgHIAHAAIAAgCQAAgKAEgFQAFgFAJAAIAFAAIAFABIAAAIIgBAAIgEgBIgEAAQgGAAgDACQgBADAAAHIAAACIAPAAIAAAHIgPAAIAAAug");
	this.shape_53.setTransform(87.3,243.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AgQAbIAAg1IAJAAIAAAIQAGgFADgBQAEgCAEAAIAEAAIADAAIAAAKIgBAAIgDgBIgFAAQgEAAgEACIgHAFIAAAlg");
	this.shape_54.setTransform(79.8,244.2);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_55.setTransform(74.1,244.2);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AgDAbIgXg1IAKAAIAQAqIARgqIAJAAIgVA1g");
	this.shape_56.setTransform(68.1,244.2);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_57.setTransform(62,244.2);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAAQgFQAAgHgEgEQgDgEgIAAQgGAAgEAEQgFAEAAAHIAeAAIAAAAg");
	this.shape_58.setTransform(52.3,244.2);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_59.setTransform(46.7,244.2);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AgRAXQgFgFAAgLIAAgiIAKAAIAAAeIAAAHIACAFQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIAGACQADgBAEgCIAIgEIAAgoIAJAAIAAA1IgJAAIAAgFIgJAFQgEACgEAAQgJAAgFgFg");
	this.shape_60.setTransform(40.8,244.3);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AgRAVQgHgIAAgNQAAgMAHgIQAHgIAKAAQAMAAAGAIQAHAIAAAMQAAANgHAIQgGAIgMAAQgKAAgHgIgAgKgPQgFAFAAAKQAAAKAFAGQAEAFAGAAQAHAAAFgFQAEgGAAgKQAAgKgEgFQgFgFgHAAQgGAAgEAFg");
	this.shape_61.setTransform(34.5,244.2);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AAXAkIAAg9IgVApIgEAAIgUgpIAAA9IgJAAIAAhHIANAAIASAnIATgnIANAAIAABHg");
	this.shape_62.setTransform(27.2,243.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(4));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(20,233.9,199.9,17.2);


// stage content:
(lib.JOB0000_template_300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{loop:1,replay:41});

	// timeline functions:
	this.frame_0 = function() {
		this.pauseFor = function(mc,i){
			mc.stop();
			console.log("Paused : "+i.toString()+"s. ");
			exportRoot.t=setTimeout(function(){
				mc.play();
			}, i*1000);
			
		}
		this.breakPauseFor = function(){
			clearTimeout(exportRoot.t);
		}
		this.loop = 1;
		
		//preview compatible
	}
	this.frame_17 = function() {
		this.pauseFor(this,0.4);
	}
	this.frame_24 = function() {
		this.pauseFor(this,0.5);
	}
	this.frame_37 = function() {
		if(this.loop >= 1) { this.stop();}
		else {
			this.loop++;
			this.pauseFor(this,5.0);
		}
	}
	this.frame_48 = function() {
		this.gotoAndPlay("loop");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(17).call(this.frame_17).wait(7).call(this.frame_24).wait(13).call(this.frame_37).wait(11).call(this.frame_48).wait(3));

	// BORDER
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDgA3RTYMAujAAAMAAAgmvMgujAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(51));

	// bg_white
	this.instance = new lib.bg_white();
	this.instance.parent = this;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1).to({alpha:0},11).to({_off:true},1).wait(37));

	// Layer_1
	this.hitbox = new lib.tnc_hitbox();
	this.hitbox.name = "hitbox";
	this.hitbox.parent = this;
	this.hitbox._off = true;
	new cjs.ButtonHelper(this.hitbox, 0, 1, 2, false, new lib.tnc_hitbox(), 3);

	this.timeline.addTween(cjs.Tween.get(this.hitbox).wait(2).to({_off:false},0).wait(49));

	// cta
	this.cta = new lib.cta();
	this.cta.name = "cta";
	this.cta.parent = this;
	this.cta.setTransform(-120,47);
	this.cta._off = true;

	this.timeline.addTween(cjs.Tween.get(this.cta).wait(29).to({_off:false},0).to({x:20},5,cjs.Ease.get(1)).wait(17));

	// t1
	this.instance_1 = new lib.t1();
	this.instance_1.parent = this;
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(18).to({_off:false},0).to({alpha:1},5).wait(28));

	// logo
	this.logo = new lib.logo();
	this.logo.name = "logo";
	this.logo.parent = this;
	this.logo.setTransform(260,218);
	this.logo._off = true;

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(2).to({_off:false},0).wait(49));

	// bg1
	this.instance_2 = new lib.bg_ani();
	this.instance_2.parent = this;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(2).to({_off:false},0).wait(49));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,125,300,250);
// library properties:
lib.properties = {
	id: 'B3851A42B7674FAC86E2F17FA24F2560',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"./bg.jpg", id:"bg"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['B3851A42B7674FAC86E2F17FA24F2560'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;